### ISSUE TITLE
Environment configuration

### ISSUE THREAD

**Issue by saniistamar** [binusgdc/VCPA#23]
While the token has since been moved out to env: https://github.com/binusgdc/VCPA/commit/8e8102680051db08ca1b0b1b131368efa2f3d818 other configuration still resides in `config.json`. This doesn't work well when deploying on platforms that do not allow such control. There should be a way to inject all configuration through the environment, or if it is not essential for the app to function, provided at run-time through user input.

**Comment by 500-internal-server-error** [comment]
Damn, we went [full circle](https://github.com/binusgdc/VCPA/commit/99bc7f43469c8a35992b640ab50e78f68a87e3a3)
![](https://i.imgur.com/6q7dYFo.png)

**Comment by saniistamar** [comment]
LMFAO

**Comment by saniistamar** [comment]
closing, we can live with docker volumes for now.
