### ISSUE TITLE
Towards CI/CD: Volume-friendly disk IO

### ISSUE THREAD

**Issue by saniistamar** [binusgdc/VCPA#31]
We rely on numerous files to read/write on disk at runtime: 
- `config.json`
- migrations
- sqlite db file
- CSV output

A volume is a method of binding a container's filesystem to the host filesystem, which is a necessity here so that we can access the data written by the app, as well as provide configuration files to configure runtime behavior.

Several issues exist with the current configuration in using volumes:
- the migrations are included in the repository i.e. they are considered "source code". However they exist in the same path as the sqlite db folder `/data`. This causes issues when binding the `/data` folder: the migrations cannot be read since the internal path is replaced with the bound path.
- the config file is not in a folder, and so cannot be bound.
- csv output is fine, actually

**Comment by 500-internal-server-error** [comment]
We could have a `config` folder similar to how we already have a `run` folder to store runtime-generated files. Unfortunately "migrations" is not a very descriptive name: what is it migrating, from where to where?

Additionally, what is the `data` folder for? Why not place it in `run`?

**Comment by saniistamar** [comment]
migrations are for db migrations, in the way webapp frameworks have a "migrations" folder. data is just for the database. Why not use run? no reason. We might actually want to just use 1 folder for files used at runtime that are **not** in the source code..?

**Comment by 500-internal-server-error** [comment]
Mixing runtime-generated files and config files sounds like a recipe for a big mess. We can have a single top level folder for ease of mapping, but at least have them separated in `data/config` and `data/run` for example.

**Comment by saniistamar** [comment]
A single folder doesn't really change the difficulty of mapping. Okay, what about folders as following:
- migrations -> this is not mapped, just to hold db migrations. If you like we can name this db_migrations.
- config -> containing human-readable configuration files, written/read at runtime 
- run -> runtime write output

thoughts?
