### ISSUE TITLE
Output is using the wrong locale

### ISSUE THREAD

**Issue by 500-internal-server-error** [binusgdc/VCPA#9]
This issue packs several changes that need to be made into a single general issue. The bot currently uses a mixture of locale formats, however it has been determined that it is best to use a single locale format, `id-ID`. This involves:

1. Changing time zones to UTC+7.
2. Changing decimal separators to be commas (e.g. `0,995`)
3. Changing outputs to be semicolon delimited (e.g. `255;0,99;other`)

These changes would lead to a better future maintenance experience.

**Comment by MrMissx** [comment]
How about implementing a container with docker to isolate the timezones?
So, no need to set a locale manually on code

**Comment by 500-internal-server-error** [comment]
A docker container would be a nice addition to have better control of the execution environment. The bot can then simply use local time.
